运营接口切换cdn&换工具接口
Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue pull request #107
Opened 2024-12-16 16:41 UTC by phidiaLam

2024-12-22 03:55 UTC, Yun-Shan requested changes

2024-12-22 03:55 UTC, Yun-Shan commented on src/popup/App.vue
> +                  })[0].url
`filter`可以改用`find`

2024-12-22 03:55 UTC, Yun-Shan commented on src/popup/App.vue
>        ServerUtil.getServerDataSourceInfo().then((data) => {
这个then改用await的形式吧，少套一层

2024-12-22 03:55 UTC, Yun-Shan commented on src/popup/App.vue
>        ServerUtil.getThirdPartyToolsInfo().then((data) => {
同上

2024-12-22 03:55 UTC, Yun-Shan commented on src/popup/App.vue
> +              if (isRepeat < 0) {
可以用`some`代替`findIndex`

2024-12-22 03:55 UTC, Yun-Shan commented on src/popup/App.vue
>            }
这段看起来有点乱，我也不知道之前为啥要这样做，看起来好像可以直接用新列表覆盖旧列表再插入默认值？  
上面的`initSourceJump`也有这个问题，以及这俩的重复度好高，有没有合并的可能性(

2024-12-22 11:28 UTC, Yun-Shan approved these changes

2024-12-25 02:48 UTC, ablupi approved these changes

2025-01-05 07:29 UTC, merged