对接服务端信息
Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue pull request #58
Opened 2022-08-16 05:00 UTC by phidiaLam

2022-08-16 07:57 UTC, phidiaLam commented on src/components/timeline/TimeLine.vue
> +      element-loading-text="【如果你看到这条信息超过1分钟，去*龙门粗口*看看网络有没 有*龙门粗口*正常连接】">
```suggestion
      element-loading-text="【如果你看到这条信息超过1分钟，去*龙门粗口*看看网络有没有*龙门粗口*正常连接】">
```

2022-08-16 08:21 UTC, Yun-Shan requested changes

2022-08-16 08:21 UTC, Yun-Shan commented on src/components/timeline/TimeLine.vue
> +      isNew: true,
默认true会导致正在请求中的时候显示有新版本(要不要把那个正在请求的蒙版再调得不透明一点)，然后如果版本信息请求失败的话 应该把这个设为false

2022-08-16 08:21 UTC, Yun-Shan commented on src/components/timeline/TimeLine.vue
> +      element-loading-text="【如果你看到这条信息超过1分钟，去*龙门粗口*看看网络有没 有*龙门粗口*正常连接】">
多了个空格

2022-08-16 08:21 UTC, Yun-Shan commented on src/popup/App.vue
>        this.drawer = !this.drawer;
getVideoJump()是异步的，提前置为true是否会有问题。
然后getVideoJump里面是用的push而非重置数组，多次调用(看起来每次打开都会调用)会有问题。

2022-08-16 08:52 UTC, phidiaLam commented on src/components/timeline/TimeLine.vue
> +      isNew: true,
请求失败兜底请求的是本地的，本地版本是9.9.9。为了引导用户可能是因为版本太久的情况

2022-08-16 08:56 UTC, phidiaLam commented on src/popup/App.vue
>        this.drawer = !this.drawer;
那就做这次打开列表点击二级菜单的时候调用一次，如果列表没关过就不再请求了

2022-08-16 08:57 UTC, phidiaLam commented on src/popup/App.vue
>        this.drawer = !this.drawer;
提前改成true没关系吧，就是数据后出来而已。不然等的话，打开不及时

2022-08-16 10:32 UTC, Yun-Shan commented on src/components/timeline/TimeLine.vue
> +      isNew: true,
> 请求失败兜底请求的是本地的，本地版本是9.9.9。为了引导用户可能是因为版本太久的情况

这实际上把网络异常情况全部归结为了版本过旧 我觉得不太合适。
如果要为版本太久兜底的话可以考虑当服务端返回特定状态码时(例如403/404)认为是过旧，但更好的办法是服务端不要删掉旧接口 让旧接口固定返回更新信息就行

2022-08-17 10:08 UTC, phidiaLam commented on src/components/timeline/TimeLine.vue
> +      isNew: true,
这个明天我看看改一下吧

2022-08-23 14:47 UTC, Yun-Shan requested changes

2022-08-23 14:47 UTC, Yun-Shan commented on src/common/sync/PenguinStatisticsInfo.js
> +        return this.penguinStatisticsInfo.items.filter(item => item.itemType != "RECRUIT_TAG" && ((item.pron.zh && item.pron.zh.some(x => x.replaceAll('`', '').indexOf(text) != -1)) || (item.alias.zh
这个判断条件好长啊，考不考虑优化一下可读性

2022-08-23 14:47 UTC, Yun-Shan commented on src/common/util/HttpUtil.js
> +  static async GET(url, options={}) {
等号左右加个空格好看点

2022-08-23 14:47 UTC, Yun-Shan commented on src/common/util/ServerUtil.js
> +        }
这一段还是有点怪，如果想要返回的话需要加个return。试了一下ok是false的时候.text()也可以得到response的body内容，但是如果要返回非成功响应的内容的话，下面用到的地方应该对data做一下相应的校验 目前好像没看到校验

当然目前实际没有返回，这在整个逻辑上是没问题的，不过这样就不需要else这个块了

2022-08-23 14:47 UTC, Yun-Shan commented on src/components/UpdateInfoNotice.vue
> +        });
话说上面都用await了 这里就没必要用then了吧

2022-08-23 14:47 UTC, Yun-Shan commented on src/components/timeline/TimeLine.vue
> +    <update-info-notice :updateInfo="updateInfo"></update-info-notice>
话说这个文件里不是有个isNew了吗，为啥这个文件里不用vif=isNew，反而要在那个组件里再判断一次是否显示

2022-08-24 01:10 UTC, phidiaLam commented on src/common/sync/PenguinStatisticsInfo.js
> +        return this.penguinStatisticsInfo.items.filter(item => item.itemType != "RECRUIT_TAG" && ((item.pron.zh && item.pron.zh.some(x => x.replaceAll('`', '').indexOf(text) != -1)) || (item.alias.zh
感觉已经没办法优化了，有什么建议吗
五个条件，有一个独立，其他两两一组

2022-08-25 14:49 UTC, Yun-Shan approved these changes

2022-08-25 14:58 UTC, merged